### ISSUE TITLE
The JSON for the Linux VM lab needs to be updated

### ISSUE THREAD

**Issue by smurawski** [Azure-Samples/azure-opensource-labs#26]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Use the deploy to Azure button to deploy the tailscale-private scenario.
> The home directory for the azureuser user will be owned by root, which blocks connecting with VS Code Remote SSH.

### Any log messages given by the failure
>

### Expected/desired behavior
> The user directory should be chown'd to the user (as the bicep template has been updated to do)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by asw101** [comment]
Thanks for catching this @smurawski! We forgot to build the bicep file.

```
cd linux/vm
az bicep build --file vm.bicep
```

Fixed on https://github.com/Azure-Samples/azure-opensource-labs/commit/c82dca830435852b5b74dbdc0eabb1483b61f212
