### ISSUE TITLE
Many AKS labs defaulting to unsupported versions of k8s

### ISSUE THREAD

**Issue by pauldotyu** [Azure-Samples/azure-opensource-labs#41]
> Please provide us with the following information:
> ---------------------------------------------------------------

AKS labs that default to k8s version 1.25.5 or lower in various regions need to be bumped to current versions

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

**Comment by tonybaloney** [comment]
Fixed in #54
